FROM alpine
LABEL org.opencontainers.image.authors="Eduardo Flores" \
      org.opencontainers.image.description="Container image for https://github.com/abishekvashok/cmatrix"

WORKDIR /root/cmatrix

RUN apk update && \
    apk add git autoconf automake alpine-sdk ncurses-dev ncurses-static && \
    git clone https://github.com/eduflornet/cmatrix.git && \
    cd cmatrix && \
    autoreconf -i && \
    ./configure LDFLAGS="-static" && \
    mkdir -p /usr/lib/kbd/consolefonts /usr/share/consoletrans && \
    make
CMD ["./cmatrix/cmatrix"]
